### ISSUE TITLE
不管用了么

### ISSUE THREAD

**Issue by ReceiveWind** [1431241631/autosafe#1]
弄完之后，查看手机端的健康上报记录没有

**Comment by 1431241631** [comment]
> 弄完之后，查看手机端的健康上报记录没有

按照部署方案部署，里面也有测试方法的，如果设置邮件提醒了，即使部署有问题也是会收到邮件提醒的，里面也说了是定时的，你可以看看是不是定时时间写的是第二天之类的

**Comment by ReceiveWind** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    谢谢，知道是哪里的问题了，现在我i科大客户端一天只允许打卡一次
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    在2022年1月7日 ***@***.***> 写道： 






弄完之后，查看手机端的健康上报记录没有



按照部署方案部署，里面也有测试方法的，如果设置邮件提醒了，即使部署有问题也是会收到邮件提醒的，里面也说了是定时的，你可以看看是不是定时时间写的是第二天之类的
